const auditConfig = window.CONCIERGE_CONFIG || {};
const authState = document.querySelector("#auth-state");
const traceForm = document.querySelector("#trace-form");
const traceInput = document.querySelector("#trace-id");
const auditResult = document.querySelector("#audit-result");
const recentButton = document.querySelector("#load-recent");
const recentList = document.querySelector("#recent-list");
const recentSection = document.querySelector(".recent-audits");
const logoutButton = document.querySelector("#logout");
const TOKEN_KEY = "conectatel.audit.id-token";

function escapeHtml(value) { const element = document.createElement("div"); element.textContent = String(value ?? ""); return element.innerHTML; }
function callbackUrl() { return `${window.location.origin}${window.location.pathname}`; }
function readFragmentToken() { const values = new URLSearchParams(window.location.hash.slice(1)); const token = values.get("id_token"); if (token) { sessionStorage.setItem(TOKEN_KEY, token); window.history.replaceState({}, document.title, window.location.pathname); } }
function token() { return sessionStorage.getItem(TOKEN_KEY); }
function configured() { return Boolean(auditConfig.auditApiUrl && auditConfig.auditUserPoolClientId && auditConfig.auditUserPoolDomain); }
function loginUrl() { const base = `https://${auditConfig.auditUserPoolDomain}.auth.us-east-1.amazoncognito.com/login`; const parameters = new URLSearchParams({ client_id: auditConfig.auditUserPoolClientId, response_type: "token", scope: "openid", redirect_uri: callbackUrl() }); return `${base}?${parameters}`; }
function showState() { if (!configured()) { authState.innerHTML = "<strong>Console ainda não configurada.</strong><span>Preencha os dados Cognito em config.js após o deploy SAM.</span>"; traceForm.hidden = true; recentSection.hidden = true; return; } if (!token()) { authState.innerHTML = `<strong>Autenticação necessária.</strong><span>Use uma conta do grupo <code>auditor</code> para consultar rastros.</span><a class="audit-login" href="${loginUrl()}">Entrar na console</a>`; traceForm.hidden = true; recentSection.hidden = true; return; } authState.innerHTML = "<strong>Autenticado como auditor.</strong><span>Consulta disponível para eventos persistidos no S3.</span>"; traceForm.hidden = false; recentSection.hidden = false; }
function citationList(items) { if (!items?.length) return "<p>Nenhuma fonte citada.</p>"; return `<ul>${items.map((item) => `<li><strong>${escapeHtml(item.source_file)}</strong> · ${escapeHtml(item.chunk_id)} · ${escapeHtml(item.status)}</li>`).join("")}</ul>`; }
function renderEvent(event) { const handoff = event.handoff ? `<section><h3>Handoff</h3><dl><dt>Motivo</dt><dd>${escapeHtml(event.handoff.reason)}</dd><dt>Protocolo</dt><dd>${escapeHtml(event.handoff.protocolo_atendimento || "não aplicável")}</dd><dt>Ação solicitada</dt><dd>${escapeHtml(event.handoff.requested_action)}</dd></dl></section>` : ""; auditResult.innerHTML = `<article class="audit-card"><div class="audit-decision"><span>${escapeHtml(event.decision)}</span><code>${escapeHtml(event.trace_id)}</code></div><section><h3>Pergunta</h3><p>${escapeHtml(event.question)}</p></section><section><h3>Decisão e resposta</h3><p>${escapeHtml(event.answer)}</p></section><section><h3>Fontes consultadas</h3>${citationList(event.citations)}</section><section><h3>Guardrail</h3><p>${escapeHtml(event.guardrail || "Nenhum")}</p></section>${handoff}<footer>${escapeHtml(event.timestamp)} · ${escapeHtml(event.duration_ms)} ms</footer></article>`; }
function renderRecent(items) { if (!items.length) { recentList.innerHTML = "<p>Nenhum trace persistido foi encontrado.</p>"; return; } recentList.innerHTML = `<div class="recent-table">${items.map((item) => `<button type="button" data-trace-id="${escapeHtml(item.trace_id)}"><code>${escapeHtml(item.trace_id)}</code><span>${escapeHtml(new Date(item.timestamp).toLocaleString("pt-BR"))}</span></button>`).join("")}</div>`; }

readFragmentToken(); showState();
traceForm.addEventListener("submit", async (event) => { event.preventDefault(); const traceId = traceInput.value.trim(); if (!traceId) return; auditResult.innerHTML = "<p class=\"audit-loading\">Consultando auditoria...</p>"; try { const response = await fetch(auditConfig.auditApiUrl, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` }, body: JSON.stringify({ trace_id: traceId }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Não foi possível consultar o trace."); renderEvent(payload); } catch (error) { auditResult.innerHTML = `<p class="audit-error">${escapeHtml(error.message || "Falha ao consultar auditoria.")}</p>`; } });
recentButton.addEventListener("click", async () => { if (!token()) return; recentButton.disabled = true; recentList.innerHTML = "<p class=\"audit-loading\">Carregando traces recentes...</p>"; try { const response = await fetch(`${auditConfig.auditApiUrl}/recent`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token()}` }, body: "{}" }); const payload = await response.json(); if (!response.ok) throw new Error(payload.message || "Não foi possível listar os traces."); renderRecent(payload.items || []); } catch (error) { recentList.innerHTML = `<p class="audit-error">${escapeHtml(error.message || "Falha ao listar auditoria.")}</p>`; } finally { recentButton.disabled = false; } });
recentList.addEventListener("click", (event) => { const button = event.target.closest("[data-trace-id]"); if (!button) return; traceInput.value = button.dataset.traceId; traceForm.requestSubmit(); });
logoutButton.addEventListener("click", () => { sessionStorage.removeItem(TOKEN_KEY); if (configured()) { const url = `https://${auditConfig.auditUserPoolDomain}.auth.us-east-1.amazoncognito.com/logout?${new URLSearchParams({ client_id: auditConfig.auditUserPoolClientId, logout_uri: callbackUrl() })}`; window.location.assign(url); return; } window.location.reload(); });
